import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"relative"}>
        <Image
          className={
            "h-[100%] absolute top-2/4 left-2/4 translate-x-[-50%] translate-y-[-50%]"
          }
          src={"/main-image.svg"}
          alt={"Картинка"}
          width={1920}
          height={1080}
        />
        {children}
      </body>
    </html>
  );
}