export const hotspotData = {
  homeScene: [
    {
      id: "vasiliev",
      type: "link",
      yaw: 2.4,
      pitch: -19,
      book: 1,
    },
    {
      id: "butorina",
      type: "link",
      yaw: 47,
      pitch: -28,
      book: 1,
    },
    {
      id: "lopatin",
      type: "link",
      yaw: -30,
      pitch: -25,
      book: 1,
    },
    {
      id: "romanova",
      type: "link",
      yaw: -116,
      pitch: -18,
      book: 1,
    },
    {
      id: "antonov",
      type: "link",
      yaw: 71,
      pitch: -10,
      book: 1,
    },
    {
      id: "zaitsev",
      type: "link",
      yaw: -136,
      pitch: -25,
      book: 1,
    },
    {
      id: "podshivalov",
      type: "link",
      yaw: -202,
      pitch: -21,
      book: 1,
    },
    {
      id: "lunin",
      type: "link",
      yaw: -58,
      pitch: -40,
      book: 1,
    },
    {
      id: "butikov",
      type: "link",
      yaw: -220,
      pitch: -13,
      book: 1,
    },
    {
      id: "sesonov",
      type: "link",
      yaw: -104,
      pitch: -10,
      book: 1,
    },
    {
      id: "orynbaev",
      type: "link",
      yaw: -130,
      pitch: -10,
      book: 1,
    },
  ],
};
