export const hotspotData = {
  homeScene: [
    {
      id: "vasiliev",
      type: "link",
      yaw: 2.5,
      pitch: -20,
      book: 1,
    },
    {
      id: "butorina",
      type: "link",
      yaw: 47,
      pitch: -28,
      book: 1,
    },
    {
      id: "lopatin",
      type: "link",
      yaw: -30,
      pitch: -25,
      book: 1,
    },
    {
      id: "romanova",
      type: "link",
      yaw: -118,
      pitch: -17,
      book: 1,
    },
    {
      id: "antonov",
      type: "link",
      yaw: 72,
      pitch: -10,
      book: 1,
    },
    {
      id: "zaitsev",
      type: "link",
      yaw: -134,
      pitch: -25,
      book: 1,
    },
    {
      id: "podshivalov",
      type: "link",
      yaw: -205,
      pitch: -25,
      book: 1,
    },
    {
      id: "lunin",
      type: "link",
      yaw: -55,
      pitch: -40,
      book: 1,
    },
    {
      id: "butikov",
      type: "link",
      yaw: -220,
      pitch: -13,
      book: 1,
    },
    {
      id: "sesonov",
      type: "link",
      yaw: -145,
      pitch: -10,
      book: 1,
    },
    {
      id: "orynbaev",
      type: "link",
      yaw: -130,
      pitch: -10,
      book: 1,
    },
  ],
};
